root: true
extends:
  - semistandard
  - prettier
env:
  node: true
  es2021: true
overrides:
  - files:
      - .mocharc.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
      sinon: false
