root: true
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
extends:
  - semistandard
  - plugin:prettier/recommended
rules:
  standard/computed-property-even-spacing: off
overrides:
  - files:
      - .mocharc.js
    parserOptions:
      sourceType: script
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
    globals:
      expect: false
      sinon: false
